stages:
  - test

test:
  image: maven:3-openjdk-17
  stage: test
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  before_script:
    - pwd
    - java -version
    - mvn -version
    - cd /builds/wooheaven/Spring-Study/01_Spring_Boot/01_workspace/BrewMaintenance/ && mvn clean compile --quiet
  script:
    - cd /builds/wooheaven/Spring-Study/01_Spring_Boot/01_workspace/BrewMaintenance/ && mvn test
  rules:
    - if: $CI_COMMIT_BRANCH
