spring:
  datasource:
    hikari:
      maximum-pool-size: 2
    url: jdbc:postgresql://localhost:65432/mydb
    username: myuser
    password: 123qwe
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        ddl-auto: update - 수정사항만 DB에 반영
        jdbc:
          lob:
            non_contextural: true
        show_sql: true
        format_sql: true
#        use_sql_comments: true