-- question
INSERT INTO question (subject, content, create_date, author_id) VALUES
('what is sbb.', 'I want to know sbb.', CURRENT_TIMESTAMP(), 1),
(           '2',                   '2', CURRENT_TIMESTAMP(), 1),
(           '3',                   '3', CURRENT_TIMESTAMP(), 1),
(           '4',                   '4', CURRENT_TIMESTAMP(), 1),
(           '5',                   '5', CURRENT_TIMESTAMP(), 1),
(           '6',                   '6', CURRENT_TIMESTAMP(), 1),
(           '7',                   '7', CURRENT_TIMESTAMP(), 1),
(           '8',                   '8', CURRENT_TIMESTAMP(), 1),
(           '9',                   '9', CURRENT_TIMESTAMP(), 1),
(          '10',                  '10', CURRENT_TIMESTAMP(), 1),
(          '11',                  '11', CURRENT_TIMESTAMP(), 1),
(          '12',                  '12', CURRENT_TIMESTAMP(), 1),
(          '13',                  '13', CURRENT_TIMESTAMP(), 1),
(          '14',                  '14', CURRENT_TIMESTAMP(), 1),
(          '15',                  '15', CURRENT_TIMESTAMP(), 1),
(          '16',                  '16', CURRENT_TIMESTAMP(), 1),
(          '17',                  '17', CURRENT_TIMESTAMP(), 1),
(          '18',                  '18', CURRENT_TIMESTAMP(), 1),
(          '19',                  '19', CURRENT_TIMESTAMP(), 1),
(          '20',                  '20', CURRENT_TIMESTAMP(), 1),
(          '21',                  '21', CURRENT_TIMESTAMP(), 1),
(          '22',                  '22', CURRENT_TIMESTAMP(), 1),
(          '23',                  '23', CURRENT_TIMESTAMP(), 1),
(          '24',                  '24', CURRENT_TIMESTAMP(), 1),
(          '25',                  '25', CURRENT_TIMESTAMP(), 1),
(          '26',                  '26', CURRENT_TIMESTAMP(), 1),
(          '27',                  '27', CURRENT_TIMESTAMP(), 1),
(          '28',                  '28', CURRENT_TIMESTAMP(), 1),
(          '29',                  '29', CURRENT_TIMESTAMP(), 1),
(          '30',                  '30', CURRENT_TIMESTAMP(), 1),
(          '31',                  '31', CURRENT_TIMESTAMP(), 1),
(          '32',                  '32', CURRENT_TIMESTAMP(), 1),
(          '33',                  '33', CURRENT_TIMESTAMP(), 1),
(          '34',                  '34', CURRENT_TIMESTAMP(), 1),
(          '35',                  '35', CURRENT_TIMESTAMP(), 1),
(          '36',                  '36', CURRENT_TIMESTAMP(), 1),
(          '37',                  '37', CURRENT_TIMESTAMP(), 1),
(          '38',                  '38', CURRENT_TIMESTAMP(), 1),
(          '39',                  '39', CURRENT_TIMESTAMP(), 1),
(          '40',                  '40', CURRENT_TIMESTAMP(), 1),
(          '41',                  '41', CURRENT_TIMESTAMP(), 1),
(          '42',                  '42', CURRENT_TIMESTAMP(), 1),
(          '43',                  '43', CURRENT_TIMESTAMP(), 1),
(          '44',                  '44', CURRENT_TIMESTAMP(), 1),
(          '45',                  '45', CURRENT_TIMESTAMP(), 1),
(          '46',                  '46', CURRENT_TIMESTAMP(), 1),
(          '47',                  '47', CURRENT_TIMESTAMP(), 1),
(          '48',                  '48', CURRENT_TIMESTAMP(), 1),
(          '49',                  '49', CURRENT_TIMESTAMP(), 1),
(          '50',                  '50', CURRENT_TIMESTAMP(), 1),
(          '51',                  '51', CURRENT_TIMESTAMP(), 1),
(          '52',                  '52', CURRENT_TIMESTAMP(), 1),
(          '53',                  '53', CURRENT_TIMESTAMP(), 1),
(          '54',                  '54', CURRENT_TIMESTAMP(), 1),
(          '55',                  '55', CURRENT_TIMESTAMP(), 1),
(          '56',                  '56', CURRENT_TIMESTAMP(), 1),
(          '57',                  '57', CURRENT_TIMESTAMP(), 1),
(          '58',                  '58', CURRENT_TIMESTAMP(), 1),
(          '59',                  '59', CURRENT_TIMESTAMP(), 1),
(          '60',                  '60', CURRENT_TIMESTAMP(), 1),
(          '61',                  '61', CURRENT_TIMESTAMP(), 1),
(          '62',                  '62', CURRENT_TIMESTAMP(), 1),
(          '63',                  '63', CURRENT_TIMESTAMP(), 1),
(          '64',                  '64', CURRENT_TIMESTAMP(), 1),
(          '65',                  '65', CURRENT_TIMESTAMP(), 1),
(          '66',                  '66', CURRENT_TIMESTAMP(), 1),
(          '67',                  '67', CURRENT_TIMESTAMP(), 1),
(          '68',                  '68', CURRENT_TIMESTAMP(), 1),
(          '69',                  '69', CURRENT_TIMESTAMP(), 1)
;

-- answer
INSERT INTO answer (question_q_id, content, create_date, author_id) VALUES 
(1, 'sbb is a simple basic board', '2024-11-14 22:06:01', 2) 
;

-- site_user
INSERT INTO site_user (id, email, password, username) VALUES
(1, 'wooheaven79@gmail.com', '$2a$10$fxFuRMuVNvSWiehZd1IW9.zXHdSi3riSIyHBsO0SXa.pmU1WfzsrK', 'myuser'),
(2, 'wooheaven85@gmail.com', '$2a$10$fxFuRMuVNvSWiehZd1IW9.zXHdSi3riSIyHBsO0SXa.pmU1WfzsrK', 'myuser2')
;