DROP TABLE IF EXISTS answer ;
CREATE TABLE answer (
    a_id integer generated by default as identity,
    question_q_id integer,
    create_date timestamp(6),
    modify_date timestamp(6),
    content TEXT,
    primary key (a_id)
) ;

DROP TABLE IF EXISTS question ;
CREATE TABLE question (
    q_id integer generated by default as identity, 
    create_date timestamp(6),
    modify_date timestamp(6),
    subject varchar(200),
    content TEXT, 
    primary key (q_id)
) ;
