DROP TABLE IF EXISTS dho_user cascade ;
CREATE TABLE dho_user (
    user_id varchar(3) not null,
    user_nm varchar(3),
    CREATE_date timestamp(6),
    game_id varchar(12),
    primary key (user_id)
) ;

DROP TABLE IF EXISTS to_do cascade ;
CREATE TABLE to_do (
    todo_id integer generated by default as identity,
    user_user_id varchar(3),
    content TEXT,
    CREATE_date timestamp(6),
    primary key (todo_id)
) ;

DROP TABLE IF EXISTS dho_login cascade ;
CREATE TABLE dho_login (
    num integer generated by default as identity,
    left_user_id varchar(3),
    left_user_nm varchar(3),
    right_user_id varchar(3),
    right_user_nm varchar(3),
    left_game_id varchar(12),
    right_game_id varchar(12),
    primary key (num)
) ;

DROP TABLE IF EXISTS answer ;
CREATE TABLE answer (
    a_id integer generated by default as identity, 
    question_q_id integer, 
    CREATE_date timestamp(6), 
    content TEXT, 
    primary key (a_id)
) ;

DROP TABLE IF EXISTS question ;
CREATE TABLE question (
    q_id integer generated by default as identity, 
    CREATE_date timestamp(6), 
    subject varchar(200), 
    content TEXT, 
    primary key (q_id)
) ;
