DROP TABLE IF EXISTS answer ;
CREATE TABLE answer (
    a_id integer generated by default as identity,
    question_q_id integer,
    author_id bigint,
    create_date timestamp(6),
    modify_date timestamp(6),
    content TEXT,
    primary key (a_id)
) ;

DROP TABLE IF EXISTS question ;
CREATE TABLE question (
    q_id integer generated by default as identity,
    author_id bigint,
    create_date timestamp(6),
    modify_date timestamp(6),
    subject varchar(200),
    content TEXT,
    primary key (q_id)
) ;

DROP TABLE IF EXISTS site_user ;
CREATE TABLE site_user (
    id bigint generated by default as identity,
    email varchar(255) unique,
    password varchar(255),
    username varchar(255) unique,
    primary key (id)
)